package guardias_de_seguridad;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Inconvenientes extends javax.swing.JFrame {
    
    Conexion_config db = new Conexion_config();
    java.sql.Connection conexion = db.conectar();
    
    DefaultTableModel modelo;
    
    /**
     * Creates new form Guardias
     */
    public Inconvenientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Fecha");
        modelo.addColumn("Cédula guardia");
        modelo.addColumn("Ruc empresa");
        this.table_inconvenientes.setModel(modelo);
        try {
            leerTabla();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() , "Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        title_inconvenientes = new javax.swing.JLabel();
        text_id = new javax.swing.JLabel();
        text_fecha = new javax.swing.JLabel();
        text_detalle = new javax.swing.JLabel();
        text_cedula_guardia = new javax.swing.JLabel();
        text_ruc_empresa = new javax.swing.JLabel();
        input_id = new javax.swing.JTextField();
        input_fecha = new javax.swing.JTextField();
        input_detalle = new javax.swing.JTextField();
        input_cedula_guardia = new javax.swing.JTextField();
        input_ruc_empresa = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();
        scroll_inconvenientes = new javax.swing.JScrollPane();
        table_inconvenientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inconvenientes");
        setResizable(false);

        background.setBackground(new java.awt.Color(232, 240, 242));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_inconvenientes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title_inconvenientes.setForeground(new java.awt.Color(0, 0, 0));
        title_inconvenientes.setText("Inconvenientes");
        background.add(title_inconvenientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 25, -1, -1));

        text_id.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        text_id.setForeground(new java.awt.Color(0, 0, 0));
        text_id.setText("Id");
        background.add(text_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 88, -1, -1));

        text_fecha.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        text_fecha.setForeground(new java.awt.Color(0, 0, 0));
        text_fecha.setText("Fecha");
        background.add(text_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 127, -1, -1));

        text_detalle.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        text_detalle.setForeground(new java.awt.Color(0, 0, 0));
        text_detalle.setText("Detalle");
        background.add(text_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 166, 50, -1));

        text_cedula_guardia.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        text_cedula_guardia.setForeground(new java.awt.Color(0, 0, 0));
        text_cedula_guardia.setText("Cédula guardia");
        background.add(text_cedula_guardia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, -1));

        text_ruc_empresa.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        text_ruc_empresa.setForeground(new java.awt.Color(0, 0, 0));
        text_ruc_empresa.setText("Ruc empresa");
        background.add(text_ruc_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 249, 90, -1));

        input_id.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        input_id.setForeground(new java.awt.Color(5, 55, 66));
        background.add(input_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 86, 217, 27));

        input_fecha.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        input_fecha.setForeground(new java.awt.Color(5, 55, 66));
        background.add(input_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 125, 217, 27));

        input_detalle.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        input_detalle.setForeground(new java.awt.Color(5, 55, 66));
        background.add(input_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 164, 217, 27));

        input_cedula_guardia.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        input_cedula_guardia.setForeground(new java.awt.Color(5, 55, 66));
        background.add(input_cedula_guardia, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 206, 217, 27));

        input_ruc_empresa.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        input_ruc_empresa.setForeground(new java.awt.Color(5, 55, 66));
        background.add(input_ruc_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 248, 217, 27));

        btn_registrar.setBackground(new java.awt.Color(162, 219, 250));
        btn_registrar.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.setFocusable(false);
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarMouseClicked(evt);
            }
        });
        background.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 284, 217, 33));

        table_inconvenientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Fecha", "Cédula guardia", "Ruc empresa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scroll_inconvenientes.setViewportView(table_inconvenientes);

        background.add(scroll_inconvenientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 86, 343, 198));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseClicked
        //Obtener los datos de los inputs
        String id = input_id.getText();
        String fecha = input_fecha.getText();
        String detalle = input_detalle.getText();
        String cedula_guardia = input_cedula_guardia.getText();
         String ruc_empresa = input_ruc_empresa.getText();
        //Validar que los campos no esten vacíos
        if(id.length() == 0 || fecha.length() == 0 || detalle.length() == 0 || cedula_guardia.length() == 0 ||
                ruc_empresa.length() == 0) {
            JOptionPane.showMessageDialog(null, "No debe dejar campos vacíos!", "Mensaje", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                String sql = "select transaccion_dos('" + id +"', '" + fecha + "', '" + detalle + "', "
                        + "'" + cedula_guardia + "', '" + ruc_empresa + "');";
                java.sql.Statement statement = conexion.createStatement();
                statement.executeQuery(sql);
                JOptionPane.showMessageDialog(null, "Inconveniente registrado!", "Mensaje", 
                        JOptionPane.INFORMATION_MESSAGE);
                try {
                    //Limpiar la tabla
                    for( int i = modelo.getRowCount() - 1; i >= 0; i-- ) {
                        modelo.removeRow(i);
                    }
                    //Ingresar los datos a la tabla
                    leerTabla();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage() , "Error", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage() , "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_registrarMouseClicked
    
    public void leerTabla() throws SQLException{
        try {
            String sql = " select * from inconvenente order by incon_id; ";
            java.sql.Statement statement = conexion.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            String[] filas = new String[6];
            while(rs.next()){
                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(4);
                filas[3] = rs.getString(5);
                modelo.addRow(filas);
              }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() , "Error", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inconvenientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inconvenientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inconvenientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inconvenientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inconvenientes().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JTextField input_cedula_guardia;
    private javax.swing.JTextField input_detalle;
    private javax.swing.JTextField input_fecha;
    private javax.swing.JTextField input_id;
    private javax.swing.JTextField input_ruc_empresa;
    private javax.swing.JScrollPane scroll_inconvenientes;
    private javax.swing.JTable table_inconvenientes;
    private javax.swing.JLabel text_cedula_guardia;
    private javax.swing.JLabel text_detalle;
    private javax.swing.JLabel text_fecha;
    private javax.swing.JLabel text_id;
    private javax.swing.JLabel text_ruc_empresa;
    private javax.swing.JLabel title_inconvenientes;
    // End of variables declaration//GEN-END:variables
}
